export const GET_ALL_TODOS = 'GET_ALL_TODOS';
export const UPDATE_TODO_LIST = 'UPDATE_TODO_LIST';
export const CREATE_NEW_TODO = 'CREATE_NEW_TODO';
export const FILTER_TODO_LIST = 'FILTER_TODO_LIST';
export const FILTER_SEARCH_INPUT = 'FILTER_SEARCH_INPUT';
export const FILTER_COMPLETE_TODOS = 'FILTER_COMPLETE_TODOS';
export const DELETE_ALL_TODOS = 'DELETE_ALL_TODOS';
