export const GET_ALL_TODOS = 'GET_ALL_TODOS';
export const UPDATE_TODO_LIST = 'UPDATE_TODO_LIST';
export const CREATE_NEW_TODO = 'CREATE_NEW_TODO';
export const DELETE_ALL_TODOS = 'DELETE_ALL_TODOS';
